services:
  wayback_machine_downloader:
    build:
        context: .
    tty: true
    image: wayback_machine_downloader:latest
    container_name: wayback_machine_downloader
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/build:rw
      - ./websites:/build/websites:rw
    command: --directory /build/websites ${OPTIONS} ${TARGET_URL}